### ISSUE TITLE
Detect Raspbian Jessie instead of Wheezy

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2server#10]
Currently, Raspbian is detected by presence of /usr/bin/raspi-config. Assuming this is in the same place in Raspbian Jessie, smarter detection should take place to prevent doing Jessie stuff in Wheezy or vice versa.

**Comment by knghtbrd** [comment]
I thought I replied to this earlier but I guess not.  If we detect features rather than OS releases, we can support any system we happen to be running on, insofar as it meets our expectations.  Fixing the init script for A2CLOUD should get us jessie support for that, and I think you said that A2SERVER already appears to work.

As noted elsewhere, lack of jessie support is a high priority bug now.

**Comment by IvanExpert** [comment]
I'd say Jessie compatibility is an even higher priority now that there is the Raspberry Pi Zero, which won't run Wheezy at all.

**Comment by knghtbrd** [comment]
I agree, though I've been hoping to have a Jessie-compatible version 
ready this month, and I would say that'd be done in plenty of time.  
The Pi Zero is awfully scarce for the moment.

It probably steps up the time scale for coming up with a more generic 
serial port solution though--the port typically used for A2Pi 
requires soldering, and like the A+ it has only one OTG-style USB 
port, so you're going to need a hub for most practical purposes.

Full steam ahead!  :)

Joseph

**Comment by IvanExpert** [comment]
I misspoke.

Just got a Zero. While it won't run the Raspbian Wheezy distro dated 5-5-2015 out of the box, it works fine if that distro has first been upgraded with `apt-get install raspberrypi-bootloader` (or `apt-get upgrade`, which includes it); that installs the 4.1.7 kernel and firmware. If you then stick the card in the Zero, it boots fine.

If we really want to be on the safe side, the identical firmware (kernel 4.1.13) that's on the Nov 2015 Raspbian Jessie distro can be installed with:
`rpi-update ab06f63098564665726fc8ba25a321f3ce8b8f03`

This means that all Pi's can run Wheezy as long as the distro has had an apt-get upgrade first, and so we should be able to provide a new Raspple II with the latest NOOBS that can install Wheezy with the newer firmware; and perhaps I'll look at upgrading the firmware and NOOBS using `a2server-update os` as I did for the 2B, though that was a headache. Presumably it will be easier now that there's already a mechanism for it.

On an related note, I've already changed the live installer script (and will be merging into the git tree) to support installing A2SERVER on Jessie. It works. Netatalk has to be recompiled so it links to libdb5.3, since that's what's available, rather than libdb5.1. I already uploaded a new Netatalk binary tarball for rpi-Jessie, and will also put one up for x86-Jessie as well.

So, pressure's off.

**Comment by knghtbrd** [comment]
That does take some pressure off, but I still want a jessie release 
this month if at all possible.

Joseph

**Comment by knghtbrd** [comment]
Jessie support for A2SERVER at least is resolved as of b5496b5, which obviously means that the differences needed are being detected.  Not 100% satisfied with the implementation at this time, but this issue is about doing the right thing on Jessie, not detangling our code from Debian specifically.  So I'll go ahead and close this.
