### ISSUE TITLE
deprecate or explicitly support Ubuntu for A2SERVER/A2CLOUD

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2server#11]
While A2SERVER originally targeted Ubuntu Server, it now instead targets Debian. Ubuntu should be explicitly supported and tested, or support and documentation about it should be removed, since it has an independent development trajectory.

**Comment by knghtbrd** [comment]
I'd say the current state is that Raspbian is generally assumed, 
Debian is certainly supported (and assumed to be a VM), and Ubuntu is 
legacy code.  I'm not even 100% sure Ubuntu would work right now, 
though if it doesn't, the fixes would be trivial.

Long term, I'd say a capability model is better than an OS release 
one.  I managed to break Raspple II a few times by trying to pare 
down the default Raspbian distribution and removing too much stuff, 
only to have the A2SERVER and/or A2CLOUD scripts fail (with errors 
that isn't logged and scrolls quickly offscreem) because they made 
assumptions about what the OS provided.  I'd like to fix that.

We can automate on Debian a bit, and we can automate far more on 
Raspbian, but if you haven't got needed capabilities, the scripts 
should tell you what's missing and then let you go fix it.  That gets 
us support for Most Linux distributions easily, and a few non-Linux 
as well.  If someone wants to step forward to make things work the 
Ubuntu or Fedora or whatever OS way, so be it.

I guess I'm calling for explicit Ubuntu support to be dropped, but 
implicit support for it and more to be present.

Joseph

**Comment by IvanExpert** [comment]
Sure, I'm all for it, if you want to approach it that way. (Whenever I run ./configure I'm amazed that it can accomodate all of those different tests, and that someone developed a unified way of addressing it.)

**Comment by knghtbrd** [comment]
I've written my share of configure tests.  Nothing so extravagant seems to be needed here, thankfully.  :)
