### ISSUE TITLE
A2CLOUD: provide IMAP email client

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2server#14]
Install Alpine or Mutt, plus (important) an easy configuration script, which also has preset settings for common providers. This has not been done thus far because ease of use has been a design goal and neither Alpine nor Mutt is easy to configure; Mutt is probably the nicer choice but it is entirely dependent on a separately created configuration file. A sample configuration-creator script for Mutt was created by Alistair Ross at:
http://pastebin.com/Mawvd2pZ

I have not done anything further with it, however perhaps it can be used as a starting point.

**Comment by knghtbrd** [comment]
I use mutt (and am using it to type this reply), but I have to say 
that its ability to handle remote IMAP clients is … poor.  It assumes 
the IMAP server is on the LAN and does not keep a full local cache of 
messages.  Moreover it has virtually no support whatsoever for POP3 
and it needs a config file that can get pretty complex.  I also find 
its keyboard shortcuts to be bizarre even today—I use my own.  That 
said, I could probably write a good set of mutt defaults and a 
reasonably good shell script to handle some basic setup for a user's 
private .muttrc using the SMTP patch to avoid the need for setting up 
a "sendmail" tool.  (Although I think we still wind up needing cron 
so some sendmail setup will be required at some stage for that alone.

I've not used pine since before there was alpine honestly.  That said 
I did recently install it on the Pi and can investigate.  It has 
decent enough IMAP support though I think it still doesn't cache 
messages.  Still, for IMAP navigation alone, it'd be a better choice 
than mutt, and its menus are simple and familiar even if it's been 16 
years since I have used it.

Cone's another choice.  Not as popular, but it's part of the courier 
suite.  Its IMAP is easily as strong as pine, and it's similarly 
easily used because of its heavily menu-oriented design.  Very 
clearly written to be the "free alternative" to pine, since pine was 
not exactly under a free license at the time.

Fetchmail is easy and obvious for POP3, but very few people pull 
messages via POP3 anymore.  OfflineIMAP is the solution I use for 
IMAP since mutt really wants to have local folders.  But OfflineIMAP 
is not a real trivial setup.  I'll give the latest versions a fresh 
look, along with seeing if it remains a mail synchronization tool, or 
if it now provides mail sorting as well.

Joseph

**Comment by IvanExpert** [comment]
Sounds like you're pretty familiar with the options, so I'll defer to your judgment here. In terms of A2CLOUD being the thing that gets one's Apple IIc on the internet with various text-based clients, email feels like a key missing piece, but not necessarily an easily solved one.

**Comment by knghtbrd** [comment]
This issue was moved to RasppleII/a2cloud#1
