### ISSUE TITLE
INFO: How to fix sys/cdevs.h error that prevents building on Raspbian

### ISSUE THREAD

**Issue by IvanExpert** [RasppleII/a2server#40]
Raspbian Wheezy ships broken, and if you need to build certain things, even after installing build-essential, you can still get an error that ca be fixed with:

sudo apt-get -y install --reinstall libc6-dev

I think (but can't remember for sure) that the A2CLOUD and A2SERVER installer scripts take care of this if necessary, though installing on Debian 7 i386 or Raspbian Wheezy doesn't perform it because the availability of binaries means build-essential is never installed.

**Comment by knghtbrd** [comment]
I haven't encountered the problem, perhaps because I've installed upgrades to the Feb 2015 release which probably fixed the problem.  I did start getting errors spewed about CGROUP stuff that seem to slow down boot, but once it's done deciding that that's not there, it goes on about booting just fine.  Haven't botheredto work out what that's about yet.

**Comment by knghtbrd** [comment]
This kind of info should be in the wiki.

**Comment by knghtbrd** [comment]
Now on the wiki: https://github.com/RasppleII/a2server/wiki/Fixing-sys-cdevs.h.
